mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from sistemabio import views

urlpatterns = [
    path("sistemabio/", include("sistemabio.urls")),
   #  path('',views.loggin),
    path("admin/", admin.site.urls),
   # path ("admin/loggin/",views.loggin)

]

mysite/sistemabio/urls.py
from django.urls import path

from . import views

app_name = "sistemabio"
urlpatterns = [
    path("",views.index, name="home"),
    path("signup/",views.signup, name="signup"),
    path("signin/",views.signin, name="signin"),
    path("logout/",views.signout,name="logout"),
    path("about/",views.about, name="about"),
    path("principal/",views.principal, name="principal"),
    path ("perfil_administrador", views.perfil_administrador, name="perfil_administrador"),
    path ("administradores", views.administradores, name="administradores"),

    #Inquilinos
    path("inquilinos/",views.inquilinos, name="inquilinos"),
    path("new_biometricos/", views.new_biometricos, name="new_biometricos"),
    path("new_inquilino/",views.new_inquilino, name="new_inquilino"),
    path("new_biometrico/<int:usuario_id>/", views.new_biometrico, name="new_biometrico"),

    path("search_inquilino/",views.search_inquilino, name="search_inquilino"),
    path("detail_inquilino/<int:usuario_id>/",views.detail_inquilino, name ="detail_inquilino"),
    # path("detail_inquilino2/<int:usuario_id>/<int:sesion_idu>/",views.detail_inquilino2, name ="detail_inquilino2"),
    path("delete_inquilino/<int:inquilino_id>/", views.delete_inquilino, name="delete_inquilino"),
    path("edit_inquilino/<int:usuario_id>/", views.edit_inquilino, name="edit_inquilino"),

    #Datos biométricos
    path("facial/<int:usuario_id>/",views.facial, name="facial"),
    # path("facial/<int:usuario_id>,<int:tipo_sesion_id>/",views.facial2, name="facial2"),
    # path("facial/<int:usuario_id>/<int:sesion_id>/",views.facial2, name="facial2"),
    path("voz/<int:usuario_id>/", views.voz,name="voz"),
    # path("voz/", views.voz,name="voz"),




    
] 
   

mysite/sistemabio/forms.py
from django.forms import ModelForm
from django import forms
from .models import Usuario, Sesion

class InquilinoForm(forms.ModelForm): 
    class Meta:
        model = Usuario
        fields = ['nombre','ap_paterno','ap_materno', 'curp','piso','departamento','telefono', 'correo', 'fecha_nac', 'id_perfil', 'id_status']
        widtgets={
             'fecha_nac':forms.TextInput(attrs={'class': 'form-control'})
            }
        # acepta fechas aaaa-mm-dd y dd/mm/aaaa pero no aaaa/mm/dd ni dd-mm-aaaa 
        # self.fields['fecha_nac'].widget.attrs[]
    def __init__(self, *args,**kwargs):
        super(InquilinoForm,self).__init__(*args,**kwargs)
        self.fields['nombre'].widget.attrs['class']= 'form-control'
        self.fields['ap_paterno'].widget.attrs['class']= 'form-control'
        self.fields['ap_materno'].widget.attrs['class']= 'form-control'
        self.fields['curp'].widget.attrs['class']= 'form-control'
        self.fields['piso'].widget.attrs['class']= 'form-control'
        self.fields['departamento'].widget.attrs['class']= 'form-control'
        self.fields['telefono'].widget.attrs['class']= 'form-control'
        self.fields['correo'].widget.attrs['class']= 'form-control'
        self.fields['fecha_nac'].widget.attrs['class']= 'form-control'
        self.fields['id_perfil'].widget.attrs['class']= 'form-control'
        self.fields['id_status'].widget.attrs['class']= 'form-control'
        self.fields['ap_paterno'].label= 'Apellido Paterno'
        self.fields['ap_materno'].label='Apellido Materno'
        self.fields['piso'].label='No. Piso'
        self.fields['departamento'].label= 'No. Departamento'
        self.fields['telefono'].label= 'No. Teléfono'
        self.fields['fecha_nac'].label= 'Fecha de Nacimiento'
        self.fields['id_perfil'].label= 'Perfil de Usuario'
        self.fields['id_status'].label= 'Status'
        
                                              
   
#solo usuario
class SesionForm(ModelForm):
    class Meta:
        model = Sesion
        fields = ['id_usuario']
    def __init__(self, *args,**kwargs):
         super(SesionForm,self).__init__(*args,**kwargs)
        # self.fields['id_tipo_sesion'].widget.attrs['class']='form-control'
         self.fields['id_usuario'].widget.attrs['class']= 'form-control'
#solo dato
class SesionForm2(ModelForm):
    class Meta:
        model = Sesion
        fields = ['dato' ]
    def __init__(self, *args,**kwargs):
        super(SesionForm2,self).__init__(*args,**kwargs)
        
        self.fields['dato'].widget.attrs['class']= 'form-control'
#todo el modelo
class SesionForm3(ModelForm):
    class Meta:
        model = Sesion
        fields = ['id_usuario', 'dato','id_tipo_sesion','completado']
        labels = {'completado':'Completo',}
    def __init__(self, *args,**kwargs):
         super(SesionForm3,self).__init__(*args,**kwargs)
         #Widgets son los que se van a pintan en forma de etiquetas html
         self.fields['id_usuario'].widget.attrs['class']= 'form-control' 
         self.fields['id_usuario'].label= 'Usuario'
         self.fields['dato'].widget.attrs['class']='form-control' 
         self.fields['id_tipo_sesion'].widget.value='1'
         self.fields['id_tipo_sesion'].widget.attrs['class']='form-control' 
         self.fields['id_tipo_sesion'].label= 'Tipo Session'
         #self.fields['completado'].label= 'Hecho'

mysite/sistemabio/views.py
from django.http import HttpResponseRedirect,HttpResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.template import loader
import datetime
import base64
import os
import errno
import cv2
#creatiionform
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages
from django.core.paginator import Paginator
from .models import Usuario, Sesion
from .forms import InquilinoForm, SesionForm, SesionForm2, SesionForm3


#Administrador e Index
def index(request):
     title='Index'
    # return HttpResponse("Hello, world. You're at the polls index.")
     return render (request,"sistemabio/index.html",{
          'mytitle':title
     })  
def signup(request):
        if request.method == 'GET':
            print('enviando formulario')
            title='Registrar'
            return render(request,"sistemabio/signup.html",
                         {
                              'mytitle':title,
                              'form':UserCreationForm
                         } ) 
        else:
             if request.POST["password1"] == request.POST["password2"]:
                  #register user
                  try:
                    user = User.objects.create_user(username=request.POST["username"],
                                                   password=request.POST["password1"])
                    user.save()
                    login(request, user)
                    return redirect('/sistemabio/principal/')
                   # return HttpResponse('User creado satisfactoriamente')        
                  except IntegrityError:
                       return render(request, "sistemabio/signup.html",{
                            'error': 'El user ya existe',
                            'form':UserCreationForm
                        } ) 
             return render(request, "sistemabio/signup.html",{
                            'error': 'Passwords no coinciden',
                            'form':UserCreationForm
                        } )   
 

   #return render(request, "sistemabio/signin.html",
def signin(request):
         if request.method == "GET":
            title='Iniciar sesion'
            return render(request, "sistemabio/signin.html",{
                'mytitle':title,
                'form':AuthenticationForm
            } )        
         else:
              user = authenticate( request, username=request.POST['username'], password=request.POST['password'])
              if user is None:
                return render(request, 'sistemabio/signin.html',{
                    'error': "usuario o password es incorrecto.",
                    'form': AuthenticationForm
                    })

              login(request, user)
              return redirect('/sistemabio/principal/')
            
   #return render(request, "sistemabio/signin.html",
@login_required
def principal(request):
     title='Principal Administrador'
     return render (request,"sistemabio/principal_2.html",{
          'mytitle':title
     })
@login_required
def signout(request):
     logout(request)
     messages.warning(request,"Estás desconectado ahora. Inicia sesión")
     return redirect('/sistemabio/signin/')
def about(request):
     title='About'
     return render (request,"sistemabio/about.html",{
          'mytitle':title
     })
def perfil_administrador(request):
     title='Perfil administrador'
     return render (request,"sistemabio/administradores/perfil.html",{
          'mytitle':title
     })
def administradores(request):
     title='Administradores'
     return render (request,"sistemabio/administradores/administradores.html",{
          'mytitle':title
     })
# Inquiinos
def inquilinos(request):
     inquilinos = Usuario.objects.all().order_by('id_usuario')
     paginacion = Paginator(inquilinos,20)
     page_num = request.GET.get('page')
     page = paginacion.get_page(page_num)
     title='Inquilinos'
     sesiones = Sesion.objects.all()
     return render (request,"sistemabio/inquilinos/all-inquilinos.html",{
          'mytitle':title,
          'count': paginacion.count,
          'inquilinos':inquilinos,
          'sesiones': sesiones
     })
@login_required
def new_inquilino(request):
     if request.method == "GET":
        form=  InquilinoForm
        return render(request, 'sistemabio/inquilinos/new-inquilino.html', 
                      {"form":  InquilinoForm })   
     else:
        # print(request.POST)
        # return render(request, 'sistemabio/inquilinos/new-inquilino.html', {"form":  InquilinoForm})
        # commit=False es para procesar los datos antes de guardar, se usa cuando no tienes todos tus 
        # campos llenos de ese form   new_inquilino = form.save()  new_inquilino.save()
        try:
            form = InquilinoForm(request.POST)
            if form.is_valid():
               form.save()
               # print('form ', form['nombre'].value())
               # print('form usuario : ', form['nombre'].value(),  form['ap_paterno'].value(),  form['ap_materno'].value() ) 
            print("Formulario es ", form.is_valid())
            messages.success(request," El registro ha sido un éxito.")
            inquilino = get_object_or_404(Usuario, nombre=form['nombre'].value())
            print('inquilino: ', inquilino.id_usuario)
          #   print('usuario id facial ', inquilino.id_usuario)
            personName = str(inquilino.id_usuario) + inquilino.nombre + inquilino.ap_paterno + inquilino.ap_materno
            print("Nombre de personName es: ", personName)
            dataPath = 'C:/Users/yobis/Desktop/sistemabiors/SistemaBiometricoJessi/mysite/sistemabio/static/inquilinos'
            personPath = dataPath + '/' + personName
            print("Nombre de carpeta es: ", personPath)
            try:
                 os.mkdir(personPath, mode=0o755)
                 print('Carpeta creada: ',personPath)
            except OSError as e:
                 if e.errno!=errno.EEXIST:
                      raise
            return redirect('/sistemabio/new_biometricos/')
        except ValueError:
            messages.error(request, "Error no se creo el inquilino.")
            return render(request, 'sistemabio/inquilinos/new-inquilino.html', 
                          {"form":  InquilinoForm , 
                           "error": "Error creando el inquilino."})
     
@login_required
def new_biometricos(request):
      if request.method == "GET":
         form= SesionForm
         inquilinos = Usuario.objects.all()
         return render(request, 'sistemabio/inquilinos/new-biometricos.html', 
                       {"form": SesionForm,
                        'inquilinos': inquilinos
                        })   
      else:
         form= SesionForm
         inquilinos = Usuario.objects.all()
         return render(request, 'sistemabio/inquilinos/new-biometricos.html', 
                       {"form": SesionForm,
                        'inquilinos': inquilinos
                        })  

@login_required
def new_biometrico(request, usuario_id):
     if request.method == "GET":
        inquilino = get_object_or_404(Usuario,pk=usuario_id)
        form= SesionForm(instance=inquilino)
        return render(request, 'sistemabio/inquilinos/new-biometrico.html', 
                      {"form": SesionForm, 'inquilino':inquilino,
                       })   
     else:
        # print(request.POST)
        # return render(request, 'sistemabio/inquilinos/new-inquilino.html', {"form":  InquilinoForm})
        try:
            form = SesionForm(request.POST)
            new_biometricos = form.save(commit=False)
            new_biometricos.save()
            messages.success(request," El registro biométrico ha sido un éxito.")
            return redirect('/sistemabio/new_biometrico/')
        except ValueError:
            messages.error(request, "Error no se registro el biométrico.")
            return render(request, 'sistemabio/inquilinos/new-biometrico.html', 
                          {"form":  SesionForm,
                           "error": "Error registrando el biométrico."})
        
def search_inquilino(request):
     #buscar por tipo de usuario
     busqueda = request.POST.get("buscar")
     print('nusqueda es ',busqueda)
     nombre = request.POST.get("nombre")
     print('nombre es ',nombre)
     piso = request.POST.get("piso")
     print('npiso es ',piso)
     departamento = request.POST.get("departamento")
     print('ndepartamento es ',departamento)
     inquilinos = Usuario.objects.all()
     if busqueda:
        inquilinos = Usuario.objects.filter(
            Q(piso__icontains = busqueda) | 
            Q(nombre__icontains = busqueda) |
            Q(curp__icontains = busqueda) |
            Q(departamento__icontains = busqueda)
        ).distinct()  
     if nombre:
        inquilinos = Usuario.objects.filter(
            Q(nombre__icontains = nombre) 
        ).distinct()  
        print('nombre des ',nombre)
     if piso:
        inquilinos = Usuario.objects.filter(
            Q(piso__icontains = piso) 
        ).distinct() 
        print('npiso des ',piso) 
     if departamento:
        inquilinos = Usuario.objects.filter(
            Q(departamento__icontains = departamento)
        ).distinct() 
        print('ndepartamento des ',departamento)
        print('inquilino es ',inquilinos)
    # inquilino = get_object_or_404(Usuario,pk=inquilino_para)
    #  inquilinos = Usuario.objects.filter(nombre='jessica sanchez pruebaF5')
     title='search'
     return render (request,"sistemabio/inquilinos/s-inquilinos.html",{

mysite/sistemabio/templates/sistemabio/inquilinos/all-inquilinos.html
{% extends "sistemabio/base.html" %}
{% load static %}
{% block content %}
    <header class="row" style="position: relative; height: 50vh; width: 100%;">
        <div
              class="col s12 m11 l9 xl8 "
              style="position: absolute; top: 0px; height: 120%; left: 0px; right: 40px; width: 100%;"
            > 
            <img alt="" src="{% static 'sistemabio/img/ba21_2.png' %}"
                    style="position: absolute; right: -12px; top: 20%; width: 100%; height:80%"
                >
            <img alt="" src="{% static 'sistemabio/img/ba12_2.png' %}"
                    style="position: absolute;  right: -12px; top: 0px; width: 100%; height:90%">
        </div>
        <div class="col s4 hide-on-small-only" 
            
             style="position: absolute; top: 70%; left: 80%; height: 100%; transform: translate(-50%, -50%); width: 30%;" 
        >
            <h1 class="titulo" style="font-size:40px">
              LISTADO DE <b>INQUILINOS</b>
            </h1>
            <blockquote>
              <h4 class="subtitulo black-text" style="font-size:20px">
                <b>
                  Aquí puedes consultar los registros <br /> de los Inquilinos
                </b>
              </h4>
            </blockquote>
        </div>
 <!--style="height: 100%; position: absolute; top: 0%; right: 0%;"
 style="position: absolute; top: 50%; left: 30%; height: 100%; transform: translate(-50%, -50%); width: 50%;"
 -->
        <div class=" col s12 m9 l9 xl8 white-text" style="height: 100%; position: absolute; top: 0%; right: 50%;">
          <img alt="" src="{% static 'sistemabio/img/parteba15_2.png' %}" 
          class="responsive-img" style="position: absolute; right: 0px; top: 0px; height: 120%; width: 50%;">
        </div>  
    </header>
      <br />
      <br />
      <br />
      <div class="row justify-content-end">
        <div class="col-3 align-self-end">
          <a class="waves-effect waves-light text-white btn p-2 text-center  " style="background: rgb(29, 240, 134); border-radius: 20px;"
                    href="javascript:window.history.back(); " 
                > 
            <i class="material-icons  text-white large rounded-circle btn p-2 text-center">arrow_back
            </i>       Regresar              
          </a>
        </div>
      </div>
    
      <!--div class="row justify-content-end">
        <div class="col-3 align-self-end">
        <button class="btn btn-success text-center btn p-2 " onclick="window.history.back()">
          <span class="material-symbols-rounded btn p-2  text-center text-white">
              arrow_back
          </span> Regresar 
        </button>
        </div>
      </div-->  
      
  <div class="container p-5">
        <h3 style="font-family: 'Franklin Gothic Medium'">Inquilinos registrados</h3>
         <!--h1 class="bg-info">Hola {{Administrador.name}}</h1-->
    <div class="row justify-content-end">
      <div class="col-3 align-self-center">
        <a class="btn btn-outline-warning text-center" style=" background-image: var(--bs-gradient);border-radius: 20px;"
           href="/sistemabio/new_inquilino" 
        >
          <p style="font-family: 'Franklin Gothic Medium'" >
            Añadir inquilino <i class="material-icons rounded-circle ">person_add</i>
          </p>
        </a>
      </div>
    </div>        

 <div class="row" style=" border: 0.5px solid rgb(232, 142, 7); margin: 25px 0px; background:rgb(254, 218, 151)">
   

{% for inquilino in inquilinos %}
  <div class="col-md-3">
    <br>
      <div class="card" style=" border: 0.3px solid rgb(167, 103, 6);  ">
        <div class="card-body ">
          <div class="d-flex p-1 flex-row-reverse">
            <a  href="{% url 'sistemabio:detail_inquilino' inquilino.id_usuario %}">
              
             
           
              <i class='fas fa-info-circle' style='font-size:30px'></i>
            </a> 
          </div>
           Usuario:
          <h4 class="card-title ">
           {{ inquilino.nombre}} {{ inquilino.ap_paterno}} {{ inquilino.ap_materno}}
          </h4>
          <p>Tipo de usuario: {{ inquilino.id_perfil }}</p>
          <p>Curp: {{ inquilino.curp }} </p>
          <p>No. Piso: {{ inquilino.piso }} </p>
          <p>No. Departamento: {{ inquilino.departamento }} </p>
          <p>No. Teléfono: {{ inquilino.telefono }} </p>
          <p>Correo: {{ inquilino.correo }} </p>
          <p>Fecha de nacimiento: {{inquilino.fecha_nac }}</p>
          <p>Estado: {{inquilino.id_status}}</p>
          <p>Fecha de creación: {{ inquilino.fecha_creado }}</p>
          <p>Fecha de actualización: {{ inquilino.fecha_actualizado }}</p>
          
           {% for sesion in sesiones %} 
           {% if sesion.id_usuario_id == inquilino.id_usuario %}
           <h1>Datos Biométricos</h1>
              <p>Id sesion: {{ sesion.id_sesion }}</p>
              <p>id_usuario: {{sesion.id_usuario}}</p>
              <p>id_tipo_sesion : {{sesion.id_tipo_sesion }}</p>
              <p>dato :{{sesion.dato }}</p>
              <p> fecha_creacion de usuario: {{sesion.fecha_creacion}} </p>
              <p> fecha_actualizacion de usuario: {{sesion.fecha_actualizacion}}</p>
             {% endif %} 
            
           {% endfor %} 
        </div>
      </div>
    <br>
  </div>
{% endfor %}
 
</div>
</div>
<div class="container-xl">
  <div class="table-responsive">
      <div class="table-wrapper">
          <table class="table table-bordered table-hover table-warning" >
              <thead>
                  <tr style="border-spacing: 1px;" >
                      <th style="border-spacing: 1px;" >Nombre</th>
                      <th border-left-width: 1px; >Tipo de usuario </th>
                      <th>No. Piso </th>
                      <th>No. Dep</th>
                      <th>Datos biometricos</th>
                      <th>Actions _____  </th>
                  </tr>
              </thead>
              <tbody>
                {% for inquilino in inquilinos %}
                  <tr>
                      <td><h5>{{ inquilino.nombre}} {{ inquilino.ap_paterno}} {{ inquilino.ap_materno}}</h5></td>
                      <td>{{ inquilino.id_perfil }} </td>
                      <td>{{ inquilino.piso }}</td>
                      <td>{{ inquilino.departamento }}</td>
        
                      <td>
                      {% for sesion in sesiones %}
                        {% if sesion.id_usuario_id == inquilino.id_usuario %}
                        
                          Tipo sesion: {{ sesion.id_tipo_sesion }} 
                          <input name="completado" type="checkbox" value="completado" /> 
                          <p> completado : {{sesion.completado}}</p>
                          {% if sesion.id_tipo_sesion == '1' %} 
                            {% if sesion.completado == True %}
                            <input name="completado" type=checkbox checked onclick="return false;"/>
                            {% else %}  
                            <input name="completado" type=checkbox  onclick="return false;"/>
                            {% endif %}
                          {% endif %}
                          <!-- {% if sesion.id_tipo_sesion == '2' and sesion.completado == True %}
                          <input name="completado" type=checkbox checked onclick="return false;"/>
                          {% else %}  
                          <input name="completado" type=checkbox  onclick="return false;"/>
                          {% endif %}
                          {% if sesion.id_tipo_sesion == '3' and sesion.completado == True %}
                          <input name="completado" type=checkbox checked onclick="return false;"/>
                          {% else %}  
                          <input name="completado" type=checkbox  onclick="return false;"/>
                          {% endif %} -->
                          <br> 
                        
                        {% endif %}
                        
                      {% endfor %}
                      <td>
                          <a href="{% url 'sistemabio:detail_inquilino' inquilino.id_usuario %}" style="text-decoration:none">
                            <i class="fas fa-eye" style='font-size:24px;color:rgb(61, 149, 249)'></i>
                          </a>
                          <a href="{% url 'sistemabio:edit_inquilino' inquilino.id_usuario %}" style="text-decoration:none">
                            <i class='fas fa-pencil-alt' style='font-size:24px;color:rgb(251, 227, 48)'></i>
                          </a>
                          <a href="{% url 'sistemabio:delete_inquilino' inquilino.id_usuario %}" style="text-decoration:none">
                            <i class='fas fa-trash-alt' style='font-size:24px;color:red'></i>
                          </a>
                      </td>
                  </tr>
                {% endfor %}
                          
              </tbody>
          </table>
          <div class="clearfix">
              <p>Total de registros: {{count}}  pagina numero: {{page.number}}</p>
              <div class="hint-text">Mostrando<b>5</b> out of <b>{{inquilinos |length }}</b> registros</div>
              <ul class="pagination justify-content-end " >
                  <li class="page-item "><a href="#"class="page-link bg-info"><i class="fa fa-angle-double-left"></i></a></li>
                  <li class="page-item disabled"><a href="#" class="page-link">1</a></li>
                  <li class="page-item"><a href="#" class="page-link">2</a></li>
                  <li class="page-item active"><a href="#" class="page-link">3</a></li>
                  <li class="page-item"><a href="#" class="page-link">4</a></li>
                  <li class="page-item"><a href="#" class="page-link">5</a></li>
                  <li class="page-item"><a href="#" class="page-link"><i class="fa fa-angle-double-right"></i></a></li>
              </ul>
          </div>
          
      </div>
  </div>  
</div>
{% endblock %} 

mysite/sistemabio/templates/sistemabio/inquilinos/new-biometrico.html
{% extends "sistemabio/base.html" %}
{% load static %}
{% block content %}
    <header class="row" style="position: relative; height: 50vh; width: 100%;">
        <div
          class="col s12 m11 l9 xl8 "
          style="position: absolute; top: 0px; height: 110%; left: 0px;"
        >
          <img
            alt="imagen1"
            src="{% static 'sistemabio/img/ba8.png' %}"
            class="responsive-image" 
            style="height: 90%; width: 80%; left: 0px; top: 0px; position: absolute; object-fit: cover;"
          />
        </div>
        <div class="col s12 m9 l9 xl8 white-text" 
             style="position: absolute; top: 50%; left: 30%; height: 100%; transform: translate(-50%, -50%); width: 50%;"
        >
        <br>
        <br>
            <blockquote>
                <br>
                <br>
              <h2 class="subtitulo black-text " >
                <b>
                  Aquí puedes añadir los datos <br /> biométricos
                </b>
              </h2>
            </blockquote>
        </div>
        
        <div class="col m6 l6 xl5 hide-on-small-only" style="height: 100%; position: absolute; top: 0%; right: 0%;">
          <img alt="" src="{% static 'sistemabio/img/parteba11_13.png' %}" 
          class="responsive-img" style="position: absolute; right: -5px; top: 0px; height: 100%; width: 50%;">
        </div>  
    </header>
      <br />
      <br />
      <br />
      <div class="row justify-content-end">
        <div class="col-3 align-self-end">
          <a class="waves-effect waves-light text-white btn p-2 text-center  " style="background: rgb(29, 240, 134);border-radius: 20px;"
                    href="javascript:window.history.back(); " style=""
                > 
            <i class="material-icons  text-white large rounded-circle btn p-2 text-center">arrow_back
            </i>       Regresar              
          </a>
        </div>
      </div>
      <br >
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-success  text-center" style="--bs-bg-opacity: .7;">
            <h3 class="text-white">Datos Biométricos</h3>
          </div>
          <div class="card-body text-left bg-success  p-2" style="--bs-bg-opacity: .3;">
            <form action="/sistemabio/new_biometricos/" method="POST" enctype="multipart/form-data">
              {% csrf_token %} 
                <p class="text-dark" style="font-size: 20px;">
                    Agrega por lo menos un dato biométrico
                </p>
                <div class="mb-3">
                  <br>{{form.as_p}}     
                </div>
                <div class="row text-center">
                  {% if id_tipo_sesion == 1 %}
                    <div class="col-4">
                    <label for="confirm_password"> Foto:</label>
                    <a class="waves-effect waves-light text-dark btn p-2 text-center" href="{% url 'sistemabio:facial' %}"
                      style="border-radius: 30px;">
                    
                      <i class="material-icons small rounded-circle " style="font-size:90px;"> 📷
                      </i>
                    </a>
                    </div>
                  {% elif sesion.id_tipo_sesion == 3 %}
                    <div class="col-4">
                   <label for="confirm_password">Huella:</label>
                   <a class="waves-effect waves-light text-dark btn p-2 text-center" 
                       href="#" style="border-radius: 30px;"
                     >
                     <i class="material-icons small rounded-circle " style="font-size:100px;">fingerprint
                     </i>
                   </a>
                    </div>
                  {% elif sesion.id_tipo_sesion == 2 %}
                    <div class="col-4">
                  <label for="confirm_password">Voz:</label>
                  <a class="waves-effect waves-light text-dark btn p-2 text-center" 
                      href="{% url 'sistemabio:voz' %}" style="border-radius: 30px;"
                    >
                    <i class="material-icons small rounded-circle " style="font-size:100px;">mic
                    </i>
                  </a>
                    </div>
                  {% endif %}    
                </div>
                <div class="row text-center">
                  <div class="col lg6 center">
                    ¿Deseas completar los datos biometricos restantes?
                  </div> 
                  <br>
                  <br>
                  <div class="row text-center">
                    <div class="col s6 start">
                        <a class=" btn btn-warning active" aria-current="page" href="/sistemabio/signin">
                            Si
                            <i class="material-icons right">send</i>
                        </a>
                    </div>
                    <div class="col s6 center">
                        <a class="btn btn-outline-info" href="/sistemabio/signup">
                            Más tarde
                            <i class="material-icons right">edit_note</i>
                        </a>
                    </div>
                  </div>
                </div> 
                <br>
            
              <button class="btn btn-info w-100" type="submit">
                Guardar 
                <i class="material-icons "> save</i>
              </button>
            </form>
          </div>
        </div>
      </div>
<br>
<br>

{% endblock %}
 