mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from sistemabio import views

urlpatterns = [
    path("sistemabio/", include("sistemabio.urls")),
   #  path('',views.loggin),
    path("admin/", admin.site.urls),
   # path ("admin/loggin/",views.loggin)

]

mysite/sistemabio/urls.py
from django.urls import path

from . import views

app_name = "sistemabio"
urlpatterns = [
    path("",views.index, name="home"),
    path("signup/",views.signup, name="signup"),
    path("signin/",views.signin, name="signin"),
    path("logout/",views.signout,name="logout"),
    path("about/",views.about, name="about"),
    path("principal/",views.principal, name="principal"),
    path ("perfil_administrador", views.perfil_administrador, name="perfil_administrador"),
    path ("administradores", views.administradores, name="administradores"),

    #Inquilinos
    path("inquilinos/",views.inquilinos, name="inquilinos"),
    path("new_biometricos/", views.new_biometricos, name="new_biometricos"),
    path("new_inquilino/",views.new_inquilino, name="new_inquilino"),
    path("new_biometrico/<int:usuario_id>/", views.new_biometrico, name="new_biometrico"),

    path("search_inquilino/",views.search_inquilino, name="search_inquilino"),
    path("detail_inquilino/<int:usuario_id>/",views.detail_inquilino, name ="detail_inquilino"),
    # path("detail_inquilino2/<int:usuario_id>/<int:sesion_idu>/",views.detail_inquilino2, name ="detail_inquilino2"),
    path("delete_inquilino/<int:inquilino_id>/", views.delete_inquilino, name="delete_inquilino"),
    path("edit_inquilino/<int:usuario_id>/", views.edit_inquilino, name="edit_inquilino"),

    #Datos biométricos
    path("facial/<int:usuario_id>/",views.facial, name="facial"),
    # path("facial/<int:usuario_id>,<int:tipo_sesion_id>/",views.facial2, name="facial2"),
    # path("facial/<int:usuario_id>/<int:sesion_id>/",views.facial2, name="facial2"),
    path("voz/<int:usuario_id>/", views.voz,name="voz"),
    # path("voz/", views.voz,name="voz"),




    
] 
   

mysite/sistemabio/models.py
# Create your models here.
import datetime

from django.db import models
from django.utils import timezone


from django.contrib import admin
# Create your models here.

class Usuario(models.Model):
    id_usuario = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    ap_paterno = models.CharField(max_length=15)
    ap_materno = models.CharField(max_length=15)
    #   user = models.ForeignKey(User)
    curp = models.CharField(max_length=30)
     # domicilio
    piso = models.IntegerField()
     # type: Number,
    departamento = models.IntegerField()
     # type: Number,
    telefono = models.CharField(max_length=15)
     # type: String, models.IntegerField()
    correo = models.EmailField()
    #  type: String,
    fecha_nac = models.DateField()
    fecha_creado = models.DateTimeField(auto_now_add=True)
    fecha_actualizado = models.DateTimeField(auto_now=True)
    # Campos con opciones
    CATALOGO_PERFIL = [
        ('1', 'Administrador'),
        ('2', 'Usuario Inquilino'),
        ('3', 'Usuario Visitante'),
        ('4', 'Usuario Trabajador'),
    ]
    id_perfil = models.CharField(max_length=2, choices=CATALOGO_PERFIL, default='2')
    # Campos con opciones
    CATALOGO_STATUS = [
        ('1', 'ALTA'),
        ('2', 'BAJA'),
        ('3', 'PENDIENTE'),
        ('4', 'ALTA/COMPLETO'),
    ]
    id_status = models.CharField(max_length=2, choices=CATALOGO_STATUS, default='3')

    def __str__(self):
        # return "{} {} {}". format(self.nombre, self.ap_paterno, self.ap_materno)
        return f'Id {self.id_usuario} -> {self.nombre} {self.ap_paterno} {self.ap_materno}'


class Sesion(models.Model):
    id_sesion = models.AutoField(primary_key=True)
    # Relacion 1 a muchos, 
    # donde 1 usuario puede tener muchas sesiones 
    # Una sesion solo le pertenece a un usuario
    # Una sesion forzosamente deb permanecer a un usuario
    # por lo que no debe ser valor nulo null=False
    # ni almacenar valores vacios blank=False
    id_usuario = models.ForeignKey(Usuario, 
                                   on_delete=models.CASCADE,
                                   null=False,
                                   blank=False)
    CATALOGO_TIPO_SESION = [
        ('1', 'FACIAL'),
        ('2', 'VOZ'),
        ('3', 'HUELLA'),
    ]
    id_tipo_sesion = models.CharField(max_length=2, choices=CATALOGO_TIPO_SESION)

    # id_tipo_sesion = models.IntegerField(null=False, blank=False, choices=CATALOGO_TIPO_SESION, default='4')
    completado = models.BooleanField(default=False)
    # CATALOGO_STATUS_SESION = [
    #     ('0', 'NO REGISTRADO'),
    #     ('1', 'REGISTRADO'),
    # ]
    # id_status_sesion = models.CharField(max_length=2, choices=CATALOGO_STATUS_SESION, default='0')
    dato = models.BinaryField(editable = True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)
      
    def __str__(self):
         return f'{self.id_tipo_sesion}'





# class Usuario_Tipo_Sesion(models.Model):
#     id_usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
#     id_tipo_sesion = models.ForeignKey(Usuario_Sesion, on_delete=models.CASCADE)
#     image = models.BinaryField()

#contraseña generada por default[5dias para validar el alta sino se dara de baja]
#ingresa para los metodos de inicio de sesion
#si hay datos en la bd, bienvenidos ingresa tus datos boton siguiente, 
# imagen, huella(en el sensor),voz(frase), guardado entra, los datos que esten completados[palomita]
#omitir en algun tipo de sesion, huella y voz (opcional en registro mas tarde)
# display none, administrador sin editar solo visualiza y( elimina registro de sesion, solo desbloquea el bloqueo ) ocultar botones
# inquilinos vista cambiar por tabla, perfil por usuario_(Detail)
#tabla interna de desbloqueo o bloqueo y actualizacio fexha e id de quien lo hizo
#tabla is sesion de id de usuario fecha de alta, actualizacion id de quien actualizo
# Tbl_tipo_sesion
# Idsesion
# Idusuario
# Idtiposesion
# Dato [huella, foto, audio, contraseña] clob o blob
# Fecha_alta
# Fecha_modificacion
# IdUsuario_modificacion

#  IdDato ( numero de muestra)

mysite/sistemabio/views.py
from django.http import HttpResponseRedirect,HttpResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.template import loader
import datetime
import base64
import os
import errno
import cv2
#creatiionform
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages
from django.core.paginator import Paginator
from .models import Usuario, Sesion
from .forms import InquilinoForm, SesionForm, SesionForm2, SesionForm3


#Administrador e Index
def index(request):
     title='Index'
    # return HttpResponse("Hello, world. You're at the polls index.")
     return render (request,"sistemabio/index.html",{
          'mytitle':title
     })  
def signup(request):
        if request.method == 'GET':
            print('enviando formulario')
            title='Registrar'
            return render(request,"sistemabio/signup.html",
                         {
                              'mytitle':title,
                              'form':UserCreationForm
                         } ) 
        else:
             if request.POST["password1"] == request.POST["password2"]:
                  #register user
                  try:
                    user = User.objects.create_user(username=request.POST["username"],
                                                   password=request.POST["password1"])
                    user.save()
                    login(request, user)
                    return redirect('/sistemabio/principal/')
                   # return HttpResponse('User creado satisfactoriamente')        
                  except IntegrityError:
                       return render(request, "sistemabio/signup.html",{
                            'error': 'El user ya existe',
                            'form':UserCreationForm
                        } ) 
             return render(request, "sistemabio/signup.html",{
                            'error': 'Passwords no coinciden',
                            'form':UserCreationForm
                        } )   
 

   #return render(request, "sistemabio/signin.html",
def signin(request):
         if request.method == "GET":
            title='Iniciar sesion'
            return render(request, "sistemabio/signin.html",{
                'mytitle':title,
                'form':AuthenticationForm
            } )        
         else:
              user = authenticate( request, username=request.POST['username'], password=request.POST['password'])
              if user is None:
                return render(request, 'sistemabio/signin.html',{
                    'error': "usuario o password es incorrecto.",
                    'form': AuthenticationForm
                    })

              login(request, user)
              return redirect('/sistemabio/principal/')
            
   #return render(request, "sistemabio/signin.html",
@login_required
def principal(request):
     title='Principal Administrador'
     return render (request,"sistemabio/principal_2.html",{
          'mytitle':title
     })
@login_required
def signout(request):
     logout(request)
     messages.warning(request,"Estás desconectado ahora. Inicia sesión")
     return redirect('/sistemabio/signin/')
def about(request):
     title='About'
     return render (request,"sistemabio/about.html",{
          'mytitle':title
     })
def perfil_administrador(request):
     title='Perfil administrador'
     return render (request,"sistemabio/administradores/perfil.html",{
          'mytitle':title
     })
def administradores(request):
     title='Administradores'
     return render (request,"sistemabio/administradores/administradores.html",{
          'mytitle':title
     })
# Inquiinos
def inquilinos(request):
     inquilinos = Usuario.objects.all().order_by('id_usuario')
     paginacion = Paginator(inquilinos,20)
     page_num = request.GET.get('page')
     page = paginacion.get_page(page_num)
     title='Inquilinos'
     sesiones = Sesion.objects.all()
     return render (request,"sistemabio/inquilinos/all-inquilinos.html",{
          'mytitle':title,
          'count': paginacion.count,
          'inquilinos':inquilinos,
          'sesiones': sesiones
     })
@login_required
def new_inquilino(request):
     if request.method == "GET":
        form=  InquilinoForm
        return render(request, 'sistemabio/inquilinos/new-inquilino.html', 
                      {"form":  InquilinoForm })   
     else:
        # print(request.POST)
        # return render(request, 'sistemabio/inquilinos/new-inquilino.html', {"form":  InquilinoForm})
        # commit=False es para procesar los datos antes de guardar, se usa cuando no tienes todos tus 
        # campos llenos de ese form   new_inquilino = form.save()  new_inquilino.save()
        try:
            form = InquilinoForm(request.POST)
            if form.is_valid():
               form.save()
               # print('form ', form['nombre'].value())
               # print('form usuario : ', form['nombre'].value(),  form['ap_paterno'].value(),  form['ap_materno'].value() ) 
            print("Formulario es ", form.is_valid())
            messages.success(request," El registro ha sido un éxito.")
            inquilino = get_object_or_404(Usuario, nombre=form['nombre'].value())
            print('inquilino: ', inquilino.id_usuario)
          #   print('usuario id facial ', inquilino.id_usuario)
            personName = str(inquilino.id_usuario) + inquilino.nombre + inquilino.ap_paterno + inquilino.ap_materno
            print("Nombre de personName es: ", personName)
            dataPath = 'C:/Users/yobis/Desktop/sistemabiors/SistemaBiometricoJessi/mysite/sistemabio/static/inquilinos'
            personPath = dataPath + '/' + personName
            print("Nombre de carpeta es: ", personPath)
            try:
                 os.mkdir(personPath, mode=0o755)
                 print('Carpeta creada: ',personPath)
            except OSError as e:
                 if e.errno!=errno.EEXIST:
                      raise
            return redirect('/sistemabio/new_biometricos/')
        except ValueError:
            messages.error(request, "Error no se creo el inquilino.")
            return render(request, 'sistemabio/inquilinos/new-inquilino.html', 
                          {"form":  InquilinoForm , 
                           "error": "Error creando el inquilino."})
     
@login_required
def new_biometricos(request):
      if request.method == "GET":
         form= SesionForm
         inquilinos = Usuario.objects.all()
         return render(request, 'sistemabio/inquilinos/new-biometricos.html', 
                       {"form": SesionForm,
                        'inquilinos': inquilinos
                        })   
      else:
         form= SesionForm
         inquilinos = Usuario.objects.all()
         return render(request, 'sistemabio/inquilinos/new-biometricos.html', 
                       {"form": SesionForm,
                        'inquilinos': inquilinos
                        })  

@login_required
def new_biometrico(request, usuario_id):
     if request.method == "GET":
        inquilino = get_object_or_404(Usuario,pk=usuario_id)
        form= SesionForm(instance=inquilino)
        return render(request, 'sistemabio/inquilinos/new-biometrico.html', 
                      {"form": SesionForm, 'inquilino':inquilino,
                       })   
     else:
        # print(request.POST)
        # return render(request, 'sistemabio/inquilinos/new-inquilino.html', {"form":  InquilinoForm})
        try:
            form = SesionForm(request.POST)
            new_biometricos = form.save(commit=False)
            new_biometricos.save()
            messages.success(request," El registro biométrico ha sido un éxito.")
            return redirect('/sistemabio/new_biometrico/')
        except ValueError:
            messages.error(request, "Error no se registro el biométrico.")
            return render(request, 'sistemabio/inquilinos/new-biometrico.html', 
                          {"form":  SesionForm,
                           "error": "Error registrando el biométrico."})
        
def search_inquilino(request):
     #buscar por tipo de usuario
     busqueda = request.POST.get("buscar")
     print('nusqueda es ',busqueda)
     nombre = request.POST.get("nombre")
     print('nombre es ',nombre)
     piso = request.POST.get("piso")
     print('npiso es ',piso)
     departamento = request.POST.get("departamento")
     print('ndepartamento es ',departamento)
     inquilinos = Usuario.objects.all()
     if busqueda:
        inquilinos = Usuario.objects.filter(
            Q(piso__icontains = busqueda) | 
            Q(nombre__icontains = busqueda) |
            Q(curp__icontains = busqueda) |
            Q(departamento__icontains = busqueda)
        ).distinct()  
     if nombre:
        inquilinos = Usuario.objects.filter(
            Q(nombre__icontains = nombre) 
        ).distinct()  
        print('nombre des ',nombre)
     if piso:
        inquilinos = Usuario.objects.filter(
            Q(piso__icontains = piso) 
        ).distinct() 
        print('npiso des ',piso) 
     if departamento:
        inquilinos = Usuario.objects.filter(
            Q(departamento__icontains = departamento)
        ).distinct() 
        print('ndepartamento des ',departamento)
        print('inquilino es ',inquilinos)
    # inquilino = get_object_or_404(Usuario,pk=inquilino_para)
    #  inquilinos = Usuario.objects.filter(nombre='jessica sanchez pruebaF5')
     title='search'
     return render (request,"sistemabio/inquilinos/s-inquilinos.html",{

mysite/sistemabio/templates/sistemabio/facial.html
{% extends "sistemabio/base.html" %}
{% load static %}
{% block content %}
 <!-- Webcam.min.js-->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/webcamjs/1.0.25/webcam.min.js"></script> 
      
    <header class="row" style="position: relative;  height: 50vh; width: 100%;" >
        <div
          class="col s12 m11 l9 xl8 "
          style="position: absolute; top: 0px; height: 60%; left: 0px;"
        >
          <img
            alt="imagen1"
            src="{% static 'sistemabio/img/rec5.png' %}"
            class="responsive-image" 
            style="height: 200%; width: 80%; left: 0px; top: 0px; position: absolute; object-fit: cover;"
          />
        </div>
        <div class="col s12 m9 l9 xl8 white-text" 
             style="position: absolute; top: 50%; left: 30%; height: 100%; transform: translate(-50%, -50%); width: 50%;"
        >
        <br>
              <br>
            <blockquote>
              <br>
              <h2 class="subtitulo black-text ">
                <b>
                  Rostro <br /> 
                </b>
              </h2>
            </blockquote>
        </div>
        
        <div class="col m6 l6 xl5 hide-on-small-only" style="height: 100%; position: absolute; top: 0%; right: 0%;">
          <img alt="" src="{% static 'sistemabio/img/parteba10.png' %}" 
          class="responsive-img" style="position: absolute; right: -5px; top: 0px; height: 100%; width: 50%;">
        </div>  
    </header>
      <br />
      <!--
      <br />
      -->
    
     

<div class="col-md-8 mx-auto">
  <div class="card">
    <div class="card-header bg-success text-center" style="--bs-bg-opacity: .7;">
      <h3 class="text-white">Captura el rostro
        <i class="material-icons small rounded-circle " style="font-size:40px;">face
        </i>
      </h3>
    </div>
    <div class="card-body text-left bg-success "style="--bs-bg-opacity: .3;">
      <form  method="POST" enctype="multipart/form-data" >
        {% csrf_token %} 
       
      <div class="container">
          <div class="row ">
              <div class="col">
                  <p class="text-black" style="font-family: 'Franklin Gothic Medium'; font-size: 20px;" > 
                    <b>Aquí se realiza la captura de rostro</b>
                  </p>
                  <br>
                  <p>
                    Al oprimir el boton de "Take Foto" se tomará una imagen de tu rostro, posterior a eso tendrás que oprimir el botón de aceptar para continuar con el registro.
                  </p>
                  <div class="row justify-content-md-center">
                    <div class="col-6 aling-self-center">
                      <br>
                      <div id="my_camera"></div>
                      <br>
                      <div class="d-flex justify-content-center">
                       <button type="button" class="btn btn-primary" onclick="takeSnapshotAndSend()">Capturar</button> 
                      </div>
                      <br>
                      <div id="results" ></div>
                      <br>

                      <label for="id_usuario">Usuario:</label>
                      <select class="form-control" type="text" id="id_usuario" name="id_usuario" >
                        <option value="{{inquilino.id_usuario}}" selected="selected">Id {{inquilino.id_usuario}} -> {{inquilino.id_usuario}} {{inquilino.nombre}} {{inquilino.ap_paterno}} {{inquilino.ap_materno}}</option>
                      </select readonly>
                      
                      <label for="id_tipo_sesion">Tipo de sesion:</label>
                      <select class="form-control" type="text" id="id_tipo_sesion" name="id_tipo_sesion" >
                        <option value="1" selected="selected">Tipo sesion {{sesion.id_tipo_sesion}} ->FACIAL</option>
                      </select readonly>

                      <label for="id_dato">Dato:</label>
                      <input type="text" name="dato" class="form-control" id="id_dato"/> 
                      
                      <h5></h5>
                      <!-- {{form}} -->
                        
                     <script language="JavaScript">
                       Webcam.set({
                            width: 320, 
                            height: 240,
                            image_format: 'jpeg',
                            jpeg_quality: 90
                        });
                        
                        Webcam.attach('#my_camera');
                        var numPhotos = 10; // Número total de fotos que se van a capturar
                        var photoCounter = 0; // Contador de fotos capturadas
                        const data_uri2 = [];
                        function takeSnapshotAndSend() {
                          for (var i = 0; i <numPhotos; i++) {
                            // Tomar la instantánea y obtener los datos de la imagen
                            Webcam.snap(function(data_uri) {
                              // display results in page
                              document.getElementById('results').innerHTML = 
                              // '<img id="imageprev" src="'+data_uri+'"/>';
                              '<img id="imageprev" src="'+data_uri+'"/>';
                              var valor = document.getElementById("results").innerHTML;
                              
                              console.log("valor",valor);
                              // document.getElementById("id_dato").value = valor ;
                              // console.log("valor2",valor);
                              document.getElementById("id_dato").value = data_uri ;
                              console.log("dta uri",data_uri);
                              data_uri2.push(' ' + data_uri);
                              console.log("dta uri2",data_uri2);
                              document.getElementById("id_dato").value = data_uri2 ;
                              // Incrementar el contador de fotos capturadas
                              photoCounter++;
                              console.log("Foto tomada ", photoCounter)
                            });
                          }
                          console.log("Total de Fotos tomadas ", photoCounter) 
                          print('array',data_uri2)
                        }
                      </script>
                    </div>                   
                  </div>          
                  <br>
                  <br>                  
              </div>
          </div>
       
            <button class="btn btn-info w-100" type="submit">
              Guardar 
              <i class="material-icons "> save</i>
            </button>
    
         
      
      </div>
      </form>
    </div>
  </div>
</div>
<br>


{% endblock %}

mysite/sistemabio/templates/sistemabio/principal_2.html
<!-- -->
{% extends "sistemabio/base.html" %}
{% load static %}
{% block content %}
    <div>
        <header class="row" style="position:relative; height: 50vh; width:100%">
            <br>
            <br>
           <div
              class="col s12 m11 l9 xl8 "
              style="position: absolute; top: 0px; height: 100%; left: 0px;"
            >
                <img alt="" src="{% static 'sistemabio/img/ba5.png' %}" 
                        style="position: absolute; right: 60px; top: 20%; width: 100%; height:80%"
                    >
                <img alt="" src="{% static 'sistemabio/img/ba19.png' %}"
                        style="position: absolute; right: 62px; top: 0px; width: 100%; height:90%">
                
            </div>
            <div class="col s12 m9 l9 xl8"
                style="position: absolute; top: 50%; left: 70%; transform: translate(-50%, -50%); height: 90%; width: 50%;"
            >
                <img alt=""  src="{% static 'sistemabio/img/uno.png' %}" 
                        style="position: absolute; right: 30px; top:0px;  width: 60%; height:120%;"
                    >
            </div>
            <div class="col s12 m9 l9 xl8" 
                style="position: absolute; top: 70%; left: 30%; transform: translate(-50%, -50%); height: 100%; width: 50%;"
            >
                <h1 class="text-black" style="font-family:'Franklin Gothic Medium'; font-size: 60px;">
                    <b>Administrador</b>
                </h1>
                <blockquote>
                    <p style="font-size: 30px;">Menú principal</p>
                    
                        <b>
                        Registro de información de los inquilinos del edificio de condominio
                        </b> 
                </blockquote>
            </div>
        </header>
        <main class="row" style=" border: 0.0px solid rgb(220, 220, 200); margin: 50px 0px;" >
            <div class="col s12 m6 l6 xl6">
                <div class="MenuActionContainer text-center  bg-success p-2 " style="--bs-bg-opacity: .5;">
                    <i class="material-icons text-white bg-success p-2" style="border-radius: 20px;">person</i>
                    <h5 class="text-black" style="font-family:'Franklin Gothic Medium'" ><!--, sans-serif 'Franklin Gothic Medium', Arial,Arial Narrow ;"-->  
                        <b>Inquilinos</b>
                    </h5>
                    <p class="textHeight">Aquí puedes consultar el historial de todos los registros de inquilinos, agregar nuevos y darle seguimiento...</p>
                    <a class="waves-effect waves-light text-white btn bg-success p-2 text-center " 
                        href="{% url 'sistemabio:inquilinos' %}" style="border-radius: 20px;" 
                    >
                    <!-- href="/sistemabio/inquilinosinicial" -->
                        Ver registros <i class="material-icons  text-white large rounded-circle btn bg-success p-2 text-center ">fact_check</i>
                    </a>
                </div>
            </div>
            <div class="col s12 m6 l6 xl6 align-self-center">
                <div class="MenuActionContainer bg-danger p-2 text-center " style="--bs-bg-opacity: .5;">
                    <i class="material-icons text-light bg-danger p-2 rounded-circle" style="border-radius: 20px;">person_add</i>
                    <h5 class="text-black" style="font-family: 'Franklin Gothic Medium'" >
                        <strong>Añadir Inquilino</strong>
                    </h5>
                    <p class="textHeight">Aquí puedes añadir la  
                        <br>información básica del inquilino nuevo, así como los datos biométricos... 
                    </p>
                    <!--div class="container waves-effect waves-light text-white btn bg-danger  text-center  " style="border-radius: 20px;"-->
                        
                        <a class="waves-effect waves-light text-white btn bg-danger p-2 text-center "  style="border-radius: 20px;"
                        href="/sistemabio/new_inquilino" 
                        >
                        Añadir
                        <i class="material-icons text-white rounded-circlet text-white btn bg-danger p-2 text-center  ">add</i>
                        </a>
                    <!--/div-->
                    
                </div>
            </div>
            <div class="col s12 m6 l6 xl6">
                <div class=" MenuActionContainer text-center bg-info p-2" style="--bs-bg-opacity: .8;">
                    <!-- "background: rgb(107, 234, 225)" -->
                    <i class="material-icons text-white medium  p-2 rounded-circle" style="background: rgb(6, 127, 202)">receipt_long</i>
                    <h5 class="text-black" style="font-family: 'Franklin Gothic Medium'" >
                        <b>Añadir biométricos</b>
                    </h5>
                    <p class="textHeight">Aquí puedes añadir
                        <br>los datos biométricos para asociarlos a los inquilinos...
                    </p>
                    <a class="waves-effect waves-light text-white btn p-2 text-center  " style="background:rgb(6, 127, 202);border-radius: 20px;"
                        href="/sistemabio/new_biometricos"
                        >
                            Biométrico
                            <i class="material-icons text-white rounded-circlet btn p-2 text-center ">add</i>
                    </a>
                </div>
            </div>
            <div class="col s12 m6 l6 xl6">
                <div class=" MenuActionContainer text-center  bg-warning p-2" style="--bs-bg-opacity: .5;">
                    <i class="material-icons text-white medium  bg-warning p-2 rounded-circle">search</i>
                    <h5 class="text-black" style="font-family: 'Franklin Gothic Medium'" >
                        Buscar Inquilino
                    </h5>
                    <p class="textHeight">Aquí puedes buscar un inquilino y ver su información.</p>
                    <a class="waves-effect waves-light text-white btn bg-warning p-2 text-center  " 
                    href="/sistemabio/search_inquilino"  style="border-radius: 20px;"
                    >
                        Buscar
                        <i class="material-icons  text-white large rounded-circle btn bg-warning p-2 text-center ">person_search
                        </i>
                    </a>
                </div>
            </div>
            <div class="col-2 align-self-center">
                    <div class= "MenuActionContainer text-center p-2" style="background:rgb(255, 230, 89) ">
                        <h5 class="text-black" style="font-family: 'Franklin Gothic Medium'" >
                            <b>Cerrar sesion</b>
                        </h5>
                        <a class="waves-effect waves-light text-dark btn p-2 text-center" style="background:rgb(255, 255, 0);border-radius: 20px;" 
                            href="/sistemabio/logout"
                        >
                            <i class="material-icons  text-dark large rounded-circle">logout
                            </i>
                        </a>
                    </div>
                </div>
            <!--div class="row justify-content-around">
                <div class="col-2 align-self-center">
                    <div class= "MenuActionContainer text-center p-2" style="background:rgb(255, 230, 89) ">
                        <h5 class="text-black" style="font-family: 'Franklin Gothic Medium'" >
                            <b>Cerrar sesion</b>
                        </h5>
                        <a class="waves-effect waves-light text-dark btn p-2 text-center" style="background:rgb(255, 255, 0)" 
                            href="/administradores/logout" style="border-radius: 20px;"
                        >
                            <i class="material-icons  text-dark large rounded-circle">logout
                            </i>
                        </a>
                    </div>
                </div>
            </div-->
            
        
        </main>
    </div>

{% endblock %}